### ISSUE TITLE
SheduleJob not worked on windows

### ISSUE THREAD

**Issue by MinimaJack** [LazarenkoA/prometheus_1C_exporter#12]
Запустилось только после отключения `SheduleJob`
`CPU,Procdata,disk` - отключены намеренно

```
Explorers:
  - Name: ClientLic
    Property:
      timerNotyfy: 60
  - Name: AvailablePerformance
    Property:
      timerNotyfy: 10
#  - Name: CPU
#    Property:
#      timerNotyfy: 10
#  - Name: SheduleJob
#    Property:
#      timerNotyfy: 10
  - Name: Session
    Property:
      timerNotyfy: 60
  - Name: Connect
    Property:
      timerNotyfy: 60
  - Name: SessionsData
    Property:
      timerNotyfy: 10
#  - Name: ProcData
#    Property:
#      processes:
#        - rphost
#        - ragent
#        - rmngr
#      timerNotyfy: 10
#  - Name: disk
#    Property:
#      timerNotyfy: 10
```
